# Generated by Django 4.2.16 on 2024-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_page_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, verbose_name="Slug"),
        ),
    ]
