# Generated by Django 4.2.16 on 2024-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_page_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="Slug"
            ),
        ),
    ]
